spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://${DB_POSTGRES_HOST:localhost}:5432/cvconnect-core-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9094}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      acks: all
      properties:
        retry.backoff.ms: 2000
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9094}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: core-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: ${PORT_CORE_SERVICE:8082}
  servlet:
    context-path: /core
  user_service: http://${HOST_USER_SERVICE:localhost}:${PORT_USER_SERVICE:8080}/user
  notify_service: http://${HOST_NOTIFY_SERVICE:localhost}:${PORT_NOTIFY_SERVICE:8081}/notify
  core_service: http://${HOST_CORE_SERVICE:localhost}:${PORT_CORE_SERVICE:8082}/core
  email-admin: nnmhqn2003@gmail.com

logging:
  level:
    org:
      springframework:
        security: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) [%clr(%-15.15t){magenta}] %clr(%-40.40logger{36}){cyan} : %msg%n"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  expiration: ${EXPIRATION:86400} # 1 day in seconds
  secret-key: ${SECRET_KEY:TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=}
  refresh-expiration: ${REFRESH_EXPIRATION:604800} # 7 days in seconds
  verify-expiration: ${VERIFY_EXPIRATION:172800} # 2 days in seconds
  reset-password-expiration: ${RESET_PASSWORD_EXPIRATION:3600} # 1 hour in seconds
  secret-internal: ${SECRET_INTERNAL:LmJHf7e5q3k8nPz9u2y4rXw6vT1sQ0aC3eFhJgKpR0tY=}

frontend:
  url: ${FRONTEND_URL:http://localhost:3000}

open-api:
  url-gateway-localhost: http://localhost:8888/api/v1${server.servlet.context-path}
  url-gateway-radmin: ${BE_URL:http://localhost:8888}/api/v1${server.servlet.context-path}
  url-localhost: http://localhost:${server.port}${server.servlet.context-path}
  url-radmin: ${BE_URL:http://localhost:8888}${server.servlet.context-path}

redis:
  token-key: token
kafka:
  topic:
    send-email: send-email-topic

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}
