version: '3.8'
services:
  kafka:
    image: 'bitnamilegacy/kafka:3.7.0'
    container_name: kafka-cvconnect
    hostname: kafka
    restart: unless-stopped
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - cvconnect-network
  mysql:
    image: mysql:8.0
    container_name: mysql-cvconnect
    hostname: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cvconnect-network

  redis:
    image: redis:7
    container_name: redis-cvconnect
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cvconnect-network

  mongodb:
    image: mongo:6
    container_name: mongodb-cvconnect
    hostname: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - cvconnect-network

  postgres:
    image: postgres:14
    container_name: postgres-cvconnect
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cvconnect-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch-cvconnect
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - cvconnect-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: logstash-cvconnect
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - cvconnect-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana-cvconnect
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-cvconnect:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD="123456"
    depends_on:
      - elasticsearch
    networks:
      - cvconnect-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.1
    container_name: filebeat-cvconnect
    user: root
    command: ["filebeat", "-e", "--strict.perms=false"]
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - logstash
    networks:
      - cvconnect-network

volumes:
  mysql_data:
  redis_data:
  mongo_data:
  postgres_data:
  es_data:

networks:
  cvconnect-network:
    name: cvconnect-network
    driver: bridge
