version: '3.8'
services:
  kafka:
    image: 'bitnamilegacy/kafka:3.7.0'
    container_name: kafka-cvconnect
    hostname: kafka
    restart: no
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  mysql:
    image: mysql:8.0
    container_name: mysql-cvconnect
    hostname: mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql:ro

  redis:
    image: redis:7
    container_name: redis-cvconnect
    hostname: redis
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:6
    container_name: mongodb-cvconnect
    hostname: mongo
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:14
    container_name: postgres-cvconnect
    hostname: postgres
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql:ro

#  api-gateway:
#    build:
#      context: .
#      dockerfile: api-gateway/Dockerfile
#    container_name: api-gateway
#    ports:
#      - "8888:8888"
#    environment:
#      - HOST_USER_SERVICE=user-service-cvconnect
#      - PORT_USER_SERVICE=8080
#      - HOST_NOTIFY_SERVICE=notify-service-cvconnect
#      - PORT_NOTIFY_SERVICE=8081
#      - HOST_CORE_SERVICE=core-service-cvconnect
#      - PORT_CORE_SERVICE=8082
#      - HOST_SOCKET=notify-service-cvconnect
#      - PORT_SOCKET=9090
#    depends_on:
#      - kafka
#      - mysql
#      - postgres
#      - mongodb
#      - redis
#
#  user-service:
#    build:
#      context: .
#      dockerfile: user-service/Dockerfile
#    container_name: user-service-cvconnect
#    ports:
#      - "8080:8080"
#    environment:
#      - DB_HOST=mysql-cvconnect
#      - KAFKA_HOST=kafka-cvconnect
#      - KAFKA_PORT=9092
#      - HOST_REDIS=redis-cvconnect
#      - PORT_REDIS=6379
#      - HOST_USER_SERVICE=user-service-cvconnect
#      - PORT_USER_SERVICE=8080
#      - HOST_NOTIFY_SERVICE=notify-service-cvconnect
#      - PORT_NOTIFY_SERVICE=8081
#      - HOST_CORE_SERVICE=core-service-cvconnect
#      - PORT_CORE_SERVICE=8082
#      - HOST_SOCKET=notify-service-cvconnect
#      - PORT_SOCKET=9090
#    depends_on:
#      - kafka
#      - mysql
#      - postgres
#      - mongodb
#      - redis
#
#  notify-service:
#    build:
#      context: .
#      dockerfile: notify-service/Dockerfile
#    container_name: notify-service-cvconnect
#    ports:
#      - "8081:8081"
#    environment:
#      - DB_HOST=mysql-cvconnect
#      - COLLECTION_HOST=mongodb-cvconnect
#      - KAFKA_HOST=kafka-cvconnect
#      - KAFKA_PORT=9092
#      - HOST_USER_SERVICE=user-service-cvconnect
#      - PORT_USER_SERVICE=8080
#      - HOST_NOTIFY_SERVICE=notify-service-cvconnect
#      - PORT_NOTIFY_SERVICE=8081
#      - HOST_CORE_SERVICE=core-service-cvconnect
#      - PORT_CORE_SERVICE=8082
#      - HOST_SOCKET=notify-service-cvconnect
#      - PORT_SOCKET=9090
#    depends_on:
#      - kafka
#      - mysql
#      - postgres
#      - mongodb
#      - redis
#
#  core-service:
#    build:
#      context: .
#      dockerfile: core-service/Dockerfile
#    container_name: core-service-cvconnect
#    ports:
#      - "8082:8082"
#    environment:
#      - DB_HOST=postgres-cvconnect
#      - KAFKA_HOST=kafka-cvconnect
#      - KAFKA_PORT=9092
#      - HOST_USER_SERVICE=user-service-cvconnect
#      - PORT_USER_SERVICE=8080
#      - HOST_NOTIFY_SERVICE=notify-service-cvconnect
#      - PORT_NOTIFY_SERVICE=8081
#      - HOST_CORE_SERVICE=core-service-cvconnect
#      - PORT_CORE_SERVICE=8082
#      - HOST_SOCKET=notify-service-cvconnect
#      - PORT_SOCKET=9090
#    depends_on:
#      - kafka
#      - mysql
#      - postgres
#      - mongodb
#      - redis

volumes:
  mysql_data:
  redis_data:
  mongo_data:
  postgres_data:

networks:
  cvconnect-network:
    driver: bridge
