name: build-and-push.yml
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      KAFKA_HOST: kafka-cvconnect
      KAFKA_PORT: 9092
      HOST_USER_SERVICE: user-service-cvconnect
      PORT_USER_SERVICE: 8180
      HOST_NOTIFY_SERVICE: notify-service-cvconnect
      PORT_NOTIFY_SERVICE: 8181
      HOST_CORE_SERVICE: core-service-cvconnect
      PORT_CORE_SERVICE: 8182
      HOST_SOCKET: notify-service-cvconnect
      PORT_SOCKET: 9090
      HOST_REDIS: redis-cvconnect
      PORT_REDIS: 6379
      DB_POSTGRES_HOST: postgres-cvconnect
      DB_MYSQL_HOST: mysql-cvconnect
      COLLECTION_HOST: mongodb-cvconnect
      COLLECTION_PORT: 27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: temurin
#          java-version: 17
#
#      - name: Cache Maven
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-

      - name: Create Maven settings.xml
        run: |
          cd BE
          cat << 'EOF' > settings.xml
          ${{ secrets.MAVEN_SETTINGS_XML }}
          EOF

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          cd BE
          docker build \
            --build-arg KAFKA_HOST=${{ env.KAFKA_HOST }} \
            --build-arg KAFKA_PORT=${{ env.KAFKA_PORT }} \
            --build-arg DB_HOST=${{ env.DB_POSTGRES_HOST }} \
            --build-arg HOST_USER_SERVICE=${{ env.HOST_USER_SERVICE }} \
            --build-arg PORT_USER_SERVICE=${{ env.PORT_USER_SERVICE }} \
            --build-arg HOST_NOTIFY_SERVICE=${{ env.HOST_NOTIFY_SERVICE }} \
            --build-arg PORT_NOTIFY_SERVICE=${{ env.PORT_NOTIFY_SERVICE }} \
            --build-arg HOST_CORE_SERVICE=${{ env.HOST_CORE_SERVICE }} \
            --build-arg PORT_CORE_SERVICE=${{ env.PORT_CORE_SERVICE }} \
            --build-arg HOST_SOCKET=${{ env.HOST_SOCKET }} \
            --build-arg PORT_SOCKET=${{ env.PORT_SOCKET }} \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ env.HOST_CORE_SERVICE }}:latest \
            -f core-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.HOST_CORE_SERVICE }}:latest
          
          docker build \
              --build-arg DB_HOST=${{ env.DB_MYSQL_HOST }} \
              --build-arg KAFKA_HOST=${{ env.KAFKA_HOST }} \
              --build-arg KAFKA_PORT=${{ env.KAFKA_PORT }} \
              --build-arg HOST_REDIS=${{ env.HOST_REDIS }} \
              --build-arg PORT_REDIS=${{ env.PORT_REDIS }} \
              --build-arg HOST_USER_SERVICE=${{ env.HOST_USER_SERVICE }} \
              --build-arg PORT_USER_SERVICE=${{ env.PORT_USER_SERVICE }} \
              --build-arg HOST_NOTIFY_SERVICE=${{ env.HOST_NOTIFY_SERVICE }} \
              --build-arg PORT_NOTIFY_SERVICE=${{ env.PORT_NOTIFY_SERVICE }} \
              --build-arg HOST_CORE_SERVICE=${{ env.HOST_CORE_SERVICE }} \
              --build-arg PORT_CORE_SERVICE=${{ env.PORT_CORE_SERVICE }} \
              --build-arg HOST_SOCKET=${{ env.HOST_SOCKET }} \
              --build-arg PORT_SOCKET=${{ env.PORT_SOCKET }} \
              -t ${{ secrets.DOCKER_USERNAME }}/${{ env.HOST_USER_SERVICE }}:latest \
              -f user-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.HOST_USER_SERVICE }}:latest
          
          docker build \
              --build-arg DB_HOST=${{ env.DB_MYSQL_HOST }} \
              --build-arg COLLECTION_HOST=${{ env.COLLECTION_HOST }} \
              --build-arg COLLECTION_PORT=${{ env.COLLECTION_PORT }} \
              --build-arg KAFKA_HOST=${{ env.KAFKA_HOST }} \
              --build-arg KAFKA_PORT=${{ env.KAFKA_PORT }} \
              --build-arg HOST_USER_SERVICE=${{ env.HOST_USER_SERVICE }} \
              --build-arg PORT_USER_SERVICE=${{ env.PORT_USER_SERVICE }} \
              --build-arg HOST_NOTIFY_SERVICE=${{ env.HOST_NOTIFY_SERVICE }} \
              --build-arg PORT_NOTIFY_SERVICE=${{ env.PORT_NOTIFY_SERVICE }} \
              --build-arg HOST_CORE_SERVICE=${{ env.HOST_CORE_SERVICE }} \
              --build-arg PORT_CORE_SERVICE=${{ env.PORT_CORE_SERVICE }} \
              --build-arg HOST_SOCKET=${{ env.HOST_SOCKET }} \
              --build-arg PORT_SOCKET=${{ env.PORT_SOCKET }} \
              -t ${{ secrets.DOCKER_USERNAME }}/${{ env.HOST_NOTIFY_SERVICE }}:latest \
              -f notify-service/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.HOST_NOTIFY_SERVICE }}:latest
          
          docker build \
              --build-arg HOST_USER_SERVICE=${{ env.HOST_USER_SERVICE }} \
              --build-arg PORT_USER_SERVICE=${{ env.PORT_USER_SERVICE }} \
              --build-arg HOST_NOTIFY_SERVICE=${{ env.HOST_NOTIFY_SERVICE }} \
              --build-arg PORT_NOTIFY_SERVICE=${{ env.PORT_NOTIFY_SERVICE }} \
              --build-arg HOST_CORE_SERVICE=${{ env.HOST_CORE_SERVICE }} \
              --build-arg PORT_CORE_SERVICE=${{ env.PORT_CORE_SERVICE }} \
              --build-arg HOST_SOCKET=${{ env.HOST_SOCKET }} \
              --build-arg PORT_SOCKET=${{ env.PORT_SOCKET }} \
              -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest \
              -f api-gateway/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
